server:
  port: 7575

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: exchangeservice
        uri: lb://exchange-service
        predicates:
        - Path=/exchange/**
      - id: conversionservice
        uri: lb://coversion-service
        predicates:
        - Path=/conversion/**
          

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka  