server:
  port: 8081
spring:
  application:
    name: exchange-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true  
  datasource:
    name: mydb
    url: jdbc:h2:mem:mydb
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka  